name: Deploy

on: [push]

jobs:
  deploy:
    if: ${{ github.repository_owner == 'universse' }}
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: ./.github/composite-actions/install

      - name: Build & deploy
        run: |
          pnpm turbo deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
